AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Create an IAM OIDC provider for GitHub and a Role that GitHub Actions can assume
  via OIDC with least-privilege to deploy infrastructure.

Parameters:
  GitHubRepo:
    Type: String
    Description: "GitHub repo in format ‹org/repo›, e.g. your-org/infra-repo"

Resources:
  GitHubOIDCProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList: ['sts.amazonaws.com']

  GitHubActionsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub GitHubActions-${GitHubRepo}
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !GetAtt GitHubOIDCProvider.Arn
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub
                  - repo:${Repo}:ref:refs/heads/main
                  - { Repo: !Ref GitHubRepo }
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCloudFormationFullAccess
        - arn:aws:iam::aws:policy/AmazonEC2FullAccess
        - arn:aws:iam::aws:policy/AmazonECS_FullAccess
        - arn:aws:iam::aws:policy/AmazonECR_ReadOnly
        - arn:aws:iam::aws:policy/CloudWatchFullAccess

Outputs:
  OIDCProviderArn:
    Description: ARN of the created OIDC identity provider
    Value: !GetAtt GitHubOIDCProvider.Arn
  GitHubActionsRoleArn:
    Description: IAM Role ARN GitHub Actions will assume
    Value: !GetAtt GitHubActionsRole.Arn
