name: Deploy Networking Stack

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Image Gallery Infrastructure Networking Stack
    runs-on: ubuntu-latest

    steps:
      - name: Checkout infra repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials via static keys
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy infrastructure.yml
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: igallery-infrastructure
          template: infrastructure.yml
          capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
          no-fail-on-empty-changeset: 'true'
