name: Build & Push Infra Test Image
on:
  workflow_run:
    workflows: ['Deploy Infrastructure']
    types: [completed]
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  build-and-push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials 📦
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build & Push Image
        run: |
          cat > Dockerfile <<EOF
          FROM public.ecr.aws/amazonlinux/amazonlinux:2
          CMD ["echo","Infra repo placeholder image"]
          EOF
          docker build -t igallery-repo:latest .
          docker tag igallery-repo:latest ${{ steps.login-ecr.outputs.registry }}/igallery-repo:latest
          docker push ${{ steps.login-ecr.outputs.registry }}/igallery-repo:latest